services:
  - type: web
    name: wounderlust
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
